fail_on_violations: true

eslint:
  config_file: .eslintrc.json
  enabled: false

stylelint:
  config_file: .stylelintrc
  enabled: true

jshint:
  enabled: false

scss:
  enabled: false

ruby:
  enabled: false
